version: '3.8'
services:
  tomcat:
    image: tomcat:9.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target/WebEvolution.war:/usr/local/tomcat/webapps/WebEvolution.war